---
#
# SECRET* vars are encrypted with sops
#

# -- Base Docker Directory
docker_base_dir: /opt/docker

# -- Base ZFS Dataset
zfs_zpool_base_dir: /tycho

# -- Vector Aggregator Address
vector_aggregator_addr: "192.168.69.111"

# -- Vector Aggregator Port
vector_aggregator_port: "6000"
