---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Australia/Sydney
  METALLB_LB_RANGE: 10.9.4.110-10.9.4.120
  METALLB_K8S_GATEWAY_ADDR: 10.9.4.110
  METALLB_INGRESS_ADDR: 10.9.4.111
  #
  NET_NODE_CIDR: "10.9.4.0/24"
  NET_POD_CIDR: "10.42.0.0/16"
  NET_SVC_CIDR: "10.43.0.0/16"
  NET_EIP_CIDR: "192.168.69.0/24"
  #
  SVC_EMQX_ADDR: "192.168.69.110"
  SVC_HOME_ASSISTANT_ADDR: "192.168.69.103"
  SVC_PLEX_ADDR: "192.168.69.104"
  SVC_JELLYFIN_ADDR: "192.168.69.105"
  SVC_QBITTORRENT_ADDR: "192.168.69.106"
  SVC_SYSLOG_ADDR: "192.168.69.111"
  SVC_NGINX_ADDR: "192.168.69.101"
  SVC_EMBY_ADDR: "192.168.69.107"
  SVC_SMTP_RELAY_ADDR: "192.168.69.102"
