---
- hosts:
    - pikvm
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
    - name: Mount read-write
      ansible.builtin.command: /usr/local/bin/rw
      tags: always

  tasks:
    - block:
        - name: Set timezone
          community.general.timezone:
            name: "{{ timezone | default('America/New_York') }}"
        - name: Set hostname to inventory hostname
          ansible.builtin.hostname:
            name: "{{ inventory_hostname }}"
        - name: Add additional user SSH public keys
          ansible.posix.authorized_key:
            user: "{{ ansible_user }}"
            key: "{{ item }}"
          loop: "{{ ssh_authorized_keys | default([]) }}"
      rescue:
        - name: Mount read-only
          ansible.builtin.command: /usr/local/bin/ro

    - block:
        - name: Disable SSL
          ansible.builtin.template:
            src: nginx.conf.j2
            dest: /etc/kvmd/nginx/nginx.conf
            mode: 0644
      rescue:
        - name: Mount read-only
          ansible.builtin.command: /usr/local/bin/ro
      notify: Restart kvmd-nginx

    - block:
        - name: Create kvmd override configuration
          ansible.builtin.template:
            src: override.yaml.j2
            dest: /etc/kvmd/override.yaml
            mode: 0644
        - name: Load custom EDID file
          ansible.builtin.template:
            src: tc358743-edid.hex.j2
            dest: /etc/kvmd/tc358743-edid.hex
            mode: 0644
      rescue:
        - name: Mount read-only
          ansible.builtin.command: /usr/local/bin/ro
      notify: Restart kvmd

  post_tasks:
    - name: Mount read-only
      ansible.builtin.command: /usr/local/bin/ro
      tags: always

  handlers:
    - name: Restart kvmd
      ansible.builtin.systemd:
        name: kvmd.service
        state: restarted
    - name: Restart kvmd-nginx
      ansible.builtin.systemd:
        name: kvmd-nginx.service
        state: restarted
